### ISSUE TITLE
[BUG] ee_lasso_regression() missing return

### ISSUE THREAD

**Issue by yuyangstat** [pzivich/Delicatessen#41]
**Describe the bug**
The `ee_lasso_regression()` in `delicatessen.estimating_equations.regression` is missing `return` at the end.

**Comment by pzivich** [comment]
Yes it is! Thanks, I will fix in the v2.1 release

**Comment by pzivich** [comment]
I will point out a nuance with LASSO and the sandwich here. As stated in the documentation,

> As the derivative of the estimating equation for LASSO is not defined at zero, the bread (and sandwich) cannot be used to estimate the variance in all settings

So, I didn't have a check in pytest on `ee_lasso_regression` (hence why the bug). 

In general, I would recommend ridge regression currently, as convergence is a bit unstable since the derivative doesn't exist at 0 and the sandwich is invalid since the corresponding estimating equation is differentiable. I do plan on adding a twice-differentiable LASSO in the future, which should be valid with the sandwich variance estimator (that I still need to verify) #36

**Comment by yuyangstat** [comment]
Nice, good to know! Thanks!
